/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        "primary-dark": "var(--primary-dark)",
        "primary-light": "var(--primary-light)",
        accent: "var(--accent)",
        "accent-light": "var(--accent-light)",
        "accent-dark": "var(--accent-dark)",
        emerald: {
          DEFAULT: "var(--emerald)",
          mid: "var(--emerald-mid)",
          lit: "var(--emerald-lit)",
          pale: "var(--emerald-pale)",
        },
        gold: {
          DEFAULT: "var(--gold)",
          bright: "var(--gold-bright)",
          pale: "var(--gold-pale)",
        },
        ink: {
          1: "var(--ink-1)",
          2: "var(--ink-2)",
          3: "var(--ink-3)",
          4: "var(--ink-4)",
        },
        parchment: {
          1: "var(--parchment-1)",
          2: "var(--parchment-2)",
          3: "var(--parchment-3)",
          4: "var(--parchment-4)",
        },
        bg: {
          DEFAULT: "var(--bg)",
          primary: "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          tertiary: "var(--bg-tertiary)",
          card: "var(--bg-card)",
          overlay: "var(--bg-overlay)",
        },
        surface: "var(--surface)",
        text: {
          DEFAULT: "var(--text)",
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          muted: "var(--text-muted)",
          inverse: "var(--text-inverse)",
          quran: "var(--text-quran)",
        },
        border: {
          DEFAULT: "var(--border)",
          light: "var(--border-light)",
          strong: "var(--border-strong)",
        },
        mushaf: {
          bg: "var(--mushaf-bg)",
          border: "var(--mushaf-border)",
        },
        error: "var(--color-error)",
        warning: "var(--color-warning)",
        success: "var(--color-success)",
        info: "var(--color-info)",
      },
      fontFamily: {
        quran: "var(--font-quran)",
        "quran-tajweed": "var(--font-quran-tajweed)",
        ui: "var(--font-ui)",
        serif: "var(--font-serif)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        "header-h": "var(--header-h)",
        "player-h": "var(--player-h)",
        "sidebar-w": "var(--sidebar-w)",
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "var(--r-sm)",
        DEFAULT: "var(--r-md)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
        pill: "var(--r-pill)",
        full: "9999px",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        gold: "var(--shadow-gold)",
        emerald: "var(--shadow-emerald)",
        "focus-ring": "var(--focus-ring)",
      },
      transitionDuration: {
        fast: "150ms",
        mid: "220ms",
        slow: "350ms",
      },
      transitionTimingFunction: {
        ease: "cubic-bezier(0.4, 0, 0.2, 1)",
        "ease-out": "cubic-bezier(0, 0, 0.2, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      lineHeight: {
        quran: "var(--line-height-quran)",
      },
      height: {
        header: "var(--header-h)",
        player: "var(--player-h)",
      },
      width: {
        sidebar: "var(--sidebar-w)",
      },
      backgroundImage: {
        header: "var(--header-bg)",
        "header-glass": "var(--header-glass)",
        player: "var(--player-bg)",
        "player-glass": "var(--player-glass)",
        "surah-header": "var(--surah-header-bg)",
      },
      zIndex: {
        header: "100",
        sidebar: "200",
        player: "300",
        modal: "400",
        overlay: "390",
      },
    },
  },
  plugins: [],
};
