/**
 * Hisn al-Muslim (« La Citadelle du musulman »): structured, sourced data and
 * its hand-written translations.
 *
 * - /data/hisn/hisn.json: Arabic text, repetition counts, Quran and hadith
 *   references, generated by scripts/build-hisn-data.mjs;
 * - /data/hisn/{fr,en}.json: translations keyed on the item and chapter ids of
 *   that file.
 *
 * Nothing is fetched from a third party at runtime. The files are same-origin
 * JSON: the service worker keeps them after the first successful load, so a
 * chapter already opened stays readable offline.
 */

import { fetchWithTimeout } from "./fetchWithTimeout.js";

const BASE_URL = "/data/hisn";
const LOAD_TIMEOUT_MS = 10000;
const SCHEMA = "mushafplus-hisn-v1";
const TRANSLATION_SCHEMA = "mushafplus-hisn-translation-v1";

const requests = new Map();

function loadJson(file) {
  if (!requests.has(file)) {
    const request = fetchWithTimeout(
      `${BASE_URL}/${file}`,
      { headers: { Accept: "application/json" } },
      LOAD_TIMEOUT_MS,
    )
      .then((response) => {
        if (!response.ok) throw new Error(`Hisn data ${file}: HTTP ${response.status}`);
        return response.json();
      })
      .catch((error) => {
        // A failed request must not pin the failure: the reader can retry.
        requests.delete(file);
        throw error;
      });
    requests.set(file, request);
  }
  return requests.get(file);
}

/** Translations exist in French and English; Arabic readers get the English line under the Arabic text. */
export function hisnTranslationLang(uiLang) {
  return uiLang === "fr" ? "fr" : "en";
}

export async function loadHisn() {
  const data = await loadJson("hisn.json");
  if (data?.schema !== SCHEMA || !Array.isArray(data.chapters)) {
    requests.delete("hisn.json");
    throw new Error("Hisn data: unexpected format");
  }
  const chapterById = new Map(data.chapters.map((chapter) => [chapter.id, chapter]));
  const itemCount = data.chapters.reduce((total, chapter) => total + chapter.items.length, 0);
  return { chapters: data.chapters, chapterById, itemCount, stats: data.stats || {} };
}

export async function loadHisnTranslation(uiLang) {
  const lang = hisnTranslationLang(uiLang);
  const file = `${lang}.json`;
  const data = await loadJson(file);
  if (data?.schema !== TRANSLATION_SCHEMA || data.lang !== lang) {
    requests.delete(file);
    throw new Error("Hisn translation: unexpected format");
  }
  return { lang, chapters: data.chapters || {}, items: data.items || {} };
}

/** Test hook: forget what was loaded. */
export function resetHisnCache() {
  requests.clear();
}
