/**
 * Offline Latin transliteration service (Hafs numbering).
 *
 * The lines come from the assets generated by
 * scripts/build-transliteration.mjs under public/data/transliteration-en/:
 * the Quran.com v4 word-by-word transliteration, one joined line per verse,
 * keyed on the 6236 Hafs ayahs. Nothing is fetched from a third party at
 * runtime.
 *
 * Riwaya: Warsh is deliberately not served from here. A transliteration is a
 * pronunciation, and the Warsh reading differs (imala, naql, hamza
 * handling); a Hafs-derived line under Warsh Arabic would teach a recitation
 * that the mushaf above it does not show. Warsh surfaces keep the rule-based
 * approximation in src/data/transliteration.js.
 *
 * Integrity: index.json pins the SHA-256 of every per-surah file. Payloads are
 * digested before they are cached in IndexedDB, and a cached record is dropped
 * when its digest no longer matches the pinned one.
 *
 * Reading model: cards render synchronously, so a surah is loaded
 * out-of-band. getTransliterationText() answers from memory only;
 * requestTransliterationSurah() schedules the load and notifies subscribers
 * once the lines land, which is what useTransliterationData re-renders on.
 */

import { dbDelete, dbGet, dbSet } from "./dbService.js";
import { fetchWithTimeout } from "./fetchWithTimeout.js";
import SURAHS from "../data/surahs.js";

const IDB_STORE = "cache";
const ASSET_TIMEOUT_MS = 8000;
const DIR = "transliteration-en";
const SCHEMA = "mushafplus-transliteration-en-hafs-v1";
const INDEX_KEY = `${DIR}-index-v1`;
const SURAH_KEY_PREFIX = `${DIR}-s-`;

const logError = import.meta.env?.DEV ? console.error : () => {};

/** surah -> Map(ayahNumber -> text) */
const loadedSurahs = new Map();
const pendingSurahs = new Map();
const scheduled = new Set();
let indexPromise = null;
const listeners = new Set();

function emit() {
  for (const listener of listeners) listener();
}

function assetUrl(name) {
  const baseUrl = import.meta.env?.BASE_URL || "/";
  return `${baseUrl}data/${DIR}/${name}?v=${SCHEMA}`;
}

function padded(surahNumber) {
  return String(surahNumber).padStart(3, "0");
}

/**
 * Hex SHA-256, or null when WebCrypto is unavailable (insecure context). A null
 * digest means "unverifiable": the payload may serve this session but is never
 * persisted as the reader's offline transliteration.
 */
async function sha256Hex(bytes) {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle || !bytes) return null;
  try {
    const digest = await subtle.digest("SHA-256", bytes);
    return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
  } catch {
    return null;
  }
}

async function fetchAsset(name) {
  const response = await fetchWithTimeout(assetUrl(name), { cache: "force-cache" }, ASSET_TIMEOUT_MS);
  if (!response.ok) throw new Error(`Transliteration asset ${name}: ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  return { bytes, json: JSON.parse(new TextDecoder().decode(bytes)) };
}

function isValidIndex(index) {
  return (
    index?.schema === SCHEMA &&
    index?.edition?.riwaya === "hafs" &&
    Object.keys(index?.files || {}).length === 114
  );
}

async function loadIndex() {
  if (!indexPromise) {
    indexPromise = (async () => {
      try {
        const cached = await dbGet(IDB_STORE, INDEX_KEY);
        if (isValidIndex(cached?.data)) return cached.data;
      } catch {
        // Fall through to the asset.
      }
      const { json } = await fetchAsset("index.json");
      if (!isValidIndex(json)) throw new Error("Invalid transliteration index");
      dbSet(IDB_STORE, { key: INDEX_KEY, data: json, version: SCHEMA }).catch(() => {});
      return json;
    })().catch((error) => {
      indexPromise = null;
      throw error;
    });
  }
  return indexPromise;
}

/**
 * Exact completeness: a surah must cover verses 1..its Hafs total with a
 * non-empty latin line, or it is refused instead of shown.
 */
function validateSurahMap(map, surahNumber) {
  const expected = Number(SURAHS[surahNumber - 1]?.ayahs) || 0;
  if (!expected || !map || map.size !== expected) return false;
  for (let ayah = 1; ayah <= expected; ayah += 1) {
    const text = map.get(ayah);
    if (typeof text !== "string" || !text.trim()) return false;
  }
  return true;
}

function toSurahMap(rawAyahs) {
  const map = new Map();
  for (const raw of Array.isArray(rawAyahs) ? rawAyahs : []) {
    const ayahNumber = Number(raw?.ayah_number);
    const text = typeof raw?.text === "string" ? raw.text.replace(/\s+/g, " ").trim() : "";
    if (!Number.isInteger(ayahNumber) || ayahNumber < 1 || !text) continue;
    map.set(ayahNumber, text);
  }
  return map;
}

/** Latin transliteration lines for one surah, keyed by Hafs ayah number. */
export async function getTransliterationSurah(surahNumber) {
  const surah = Number(surahNumber);
  if (!Number.isInteger(surah) || surah < 1 || surah > 114) {
    throw new Error(`Invalid surah for the transliteration: ${surahNumber}`);
  }
  if (loadedSurahs.has(surah)) return loadedSurahs.get(surah);
  if (pendingSurahs.has(surah)) return pendingSurahs.get(surah);

  const promise = (async () => {
    const name = `${padded(surah)}.json`;
    const idbKey = `${SURAH_KEY_PREFIX}${surah}`;
    const index = await loadIndex();
    const pinned = index.files[name];
    if (!pinned?.sha256) throw new Error(`No pinned digest for ${name}`);

    try {
      const cached = await dbGet(IDB_STORE, idbKey);
      const cachedMap = toSurahMap(cached?.data?.ayahs);
      if (cached?.sha256 === pinned.sha256 && validateSurahMap(cachedMap, surah)) {
        loadedSurahs.set(surah, cachedMap);
        emit();
        return cachedMap;
      }
      if (cached) {
        await dbDelete(IDB_STORE, idbKey).catch(() => {});
      }
    } catch {
      // A read failure only costs a re-fetch of a local asset.
    }

    const { bytes, json: document } = await fetchAsset(name);
    const digest = await sha256Hex(bytes);
    if (digest && digest !== pinned.sha256) {
      logError(`[Transliteration] Digest mismatch for ${name}: ${digest}`);
      throw new Error(`Transliteration checksum mismatch for ${name}`);
    }
    const map = toSurahMap(document?.ayahs);
    if (!validateSurahMap(map, surah)) {
      throw new Error(`Incomplete transliteration for surah ${surah}`);
    }

    loadedSurahs.set(surah, map);
    if (digest === pinned.sha256) {
      dbSet(IDB_STORE, {
        key: idbKey,
        data: { ayahs: document.ayahs },
        sha256: digest,
        version: SCHEMA,
      }).catch(() => {});
    }
    emit();
    return map;
  })().finally(() => {
    pendingSurahs.delete(surah);
  });

  pendingSurahs.set(surah, promise);
  return promise.catch((error) => {
    logError(`[Transliteration] ${surah}: ${error?.message}`);
    throw error;
  });
}

/** The pinned line for one Hafs verse, from memory only. "" when unavailable. */
export function getTransliterationText(surahNumber, ayahNumber) {
  const map = loadedSurahs.get(Number(surahNumber));
  if (!map) return "";
  const text = map.get(Number(ayahNumber));
  return typeof text === "string" ? text : "";
}

/**
 * Load a surah out of the render pass: the first read of an unloaded surah
 * schedules the fetch, and subscribers are told when it lands so the reader
 * swaps the approximation for the pinned line without a reload.
 */
export function requestTransliterationSurah(surahNumber) {
  const surah = Number(surahNumber);
  if (!Number.isInteger(surah) || surah < 1 || surah > 114) return;
  if (loadedSurahs.has(surah) || pendingSurahs.has(surah) || scheduled.has(surah)) return;
  scheduled.add(surah);
  queueMicrotask(() => {
    scheduled.delete(surah);
    getTransliterationSurah(surah).catch(() => {});
  });
}

export function subscribeTransliteration(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

/** Attribution line for legal and about surfaces. */
export async function getTransliterationAttribution() {
  const index = await loadIndex();
  return {
    editionId: index?.edition?.id,
    name: index?.edition?.name,
    attribution: index?.attribution,
    source: index?.source,
  };
}

export async function clearTransliterationCache() {
  loadedSurahs.clear();
  pendingSurahs.clear();
  indexPromise = null;
  const keys = [INDEX_KEY];
  for (let surah = 1; surah <= 114; surah += 1) keys.push(`${SURAH_KEY_PREFIX}${surah}`);
  await Promise.all(keys.map((key) => dbDelete(IDB_STORE, key).catch(() => {})));
  emit();
  return true;
}

export default {
  getTransliterationSurah,
  getTransliterationText,
  requestTransliterationSurah,
  subscribeTransliteration,
  getTransliterationAttribution,
  clearTransliterationCache,
};
