/**
 * Contract of the Hisn al-Muslim library (public/data/hisn/): complete, well-formed,
 * sourced, and translated in both languages. The data is generated by
 * scripts/build-hisn-data.mjs; the translations are written by hand, so this is the
 * test that notices a chapter or an invocation left without one.
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { HADITH_COLLECTIONS, hadithCollectionName, hadithUrl } from "../src/data/hadithCollections.js";
import { getSurahAyahCount } from "../src/data/surahs.js";
import { buildHisnSearchIndex, searchHisnIndex } from "../src/utils/hisnSearch.js";

const read = (name) =>
  JSON.parse(fs.readFileSync(fileURLToPath(new URL(`../public/data/hisn/${name}`, import.meta.url)), "utf8"));

const hisn = read("hisn.json");
const fr = read("fr.json");
const en = read("en.json");
const items = hisn.chapters.flatMap((chapter) => chapter.items.map((item) => ({ chapter, item })));
const MATCH_MODES = new Set(["exact", "fuzzy", "partial", "fragment"]);
// Markup left in a translation, or the typical traces of a text decoded in the wrong encoding.
const BROKEN_TEXT = new RegExp("[<>]|&[a-z]+;|Ã[\\u0080-\\u00BF]|Â[\\u00A0-\\u00BF]|â€|\\uFFFD");

test("the library holds every chapter and invocation of the book, with unique ids", () => {
  assert.equal(hisn.schema, "mushafplus-hisn-v1");
  assert.equal(hisn.chapters.length, 132);
  assert.equal(items.length, 267);
  assert.equal(new Set(hisn.chapters.map((chapter) => chapter.id)).size, 132);
  assert.equal(new Set(items.map(({ item }) => item.id)).size, 267);
  for (const chapter of hisn.chapters) {
    assert.ok(chapter.ar.trim(), `chapter ${chapter.id} has an Arabic title`);
    assert.ok(chapter.items.length > 0, `chapter ${chapter.id} is not empty`);
  }
});

test("every invocation has Arabic text, a repetition count and a kind", () => {
  for (const { item } of items) {
    assert.ok(item.ar.trim(), `item ${item.id} has Arabic text`);
    assert.ok(Number.isInteger(item.n) && item.n >= 1, `item ${item.id} repeats at least once`);
    assert.ok(["dua", "quran", "mixed"].includes(item.k), `item ${item.id} kind`);
    assert.ok(!/\(\(|\)\)/.test(item.ar), `item ${item.id} has no (( )) wrapper left`);
  }
});

test("Quran references name real verses, and Quran items always carry one", () => {
  for (const { item } of items) {
    for (const [surah, from, to] of item.q || []) {
      assert.ok(Number.isInteger(surah) && surah >= 1 && surah <= 114, `item ${item.id} surah ${surah}`);
      assert.ok(from >= 1 && to >= from && to <= getSurahAyahCount(surah), `item ${item.id} verses ${surah}:${from}-${to}`);
    }
    if (item.k === "quran") assert.ok(item.q?.length, `Quran item ${item.id} names its verses`);
    if (item.k === "dua") assert.equal(item.q, undefined, `plain invocation ${item.id} claims no verse`);
  }
});

test("known verses are attached to the right invocations", () => {
  const byId = new Map(items.map(({ item }) => [item.id, item]));
  assert.deepEqual(byId.get(75).q, [[2, 255, 255]], "Ayat al-Kursi");
  assert.deepEqual(byId.get(101).q, [[2, 285, 286]], "end of Al-Baqara");
  assert.deepEqual(byId.get(76).q, [[112, 1, 4], [113, 1, 5], [114, 1, 6]], "the three Quls, whole surahs");
  assert.deepEqual(byId.get(206).q, [[43, 13, 14]], "riding: the verse starts inside 43:13");
});

test("hadith references are well formed and open the matching sunnah.com page", () => {
  let referenced = 0;
  for (const { item } of items) {
    for (const ref of item.h || []) {
      referenced += 1;
      assert.ok(HADITH_COLLECTIONS[ref.c], `item ${item.id} collection ${ref.c}`);
      assert.match(ref.n, /^\d+[a-z]?$/, `item ${item.id} hadith number ${ref.n}`);
      assert.ok(MATCH_MODES.has(ref.m), `item ${item.id} match mode ${ref.m}`);
      assert.equal(hadithUrl(ref.c, ref.n), `https://sunnah.com/${ref.c}:${ref.n}`);
      // Bukhari and Muslim carry no grading; the four Sunan carry the dataset's.
      if (ref.c === "bukhari" || ref.c === "muslim") assert.equal(ref.g, undefined);
    }
    if (item.h) assert.ok(item.h.length <= 2, `item ${item.id} lists at most two references`);
  }
  assert.ok(referenced > 250, "most invocations are referenced");
});

test("references verified by hand against sunnah.com stay in the data", () => {
  const find = (id) => items.find(({ item }) => item.id === id).item;
  // Muslim 713 was opened and read on sunnah.com; Abu Dawud 5068 and 5074 were read in the dataset text.
  assert.ok(find(20).h.some((ref) => ref.c === "muslim" && ref.n.startsWith("713")), "entering the mosque: Muslim 713");
  assert.ok(find(78).h.some((ref) => ref.c === "abudawud" && ref.n === "5068"), "morning dua: Abu Dawud 5068");
  assert.ok(find(84).h.some((ref) => ref.c === "abudawud" && ref.n === "5074"), "pardon and well-being: Abu Dawud 5074");
});

test("hadith links refuse anything that is not a numbered hadith of a known collection", () => {
  assert.equal(hadithUrl("unknown", "12"), null);
  assert.equal(hadithUrl("bukhari", "javascript:alert(1)"), null);
  assert.equal(hadithUrl("bukhari", ""), null);
  assert.equal(hadithUrl("muslim", "713a"), "https://sunnah.com/muslim:713a");
  assert.equal(hadithCollectionName("bukhari", "ar"), "صحيح البخاري");
  assert.equal(hadithCollectionName("nasai", "fr"), "Sunan an-Nasa’i");
});

for (const [lang, translation] of [["fr", fr], ["en", en]]) {
  test(`every chapter and invocation is translated in ${lang}`, () => {
    assert.equal(translation.schema, "mushafplus-hisn-translation-v1");
    assert.equal(translation.lang, lang);
    const missingChapters = hisn.chapters.filter((chapter) => !translation.chapters[chapter.id]?.trim());
    const missingItems = items.filter(({ item }) => !translation.items[item.id]?.trim());
    assert.deepEqual(missingChapters.map((chapter) => chapter.id), [], `chapters without ${lang} title`);
    assert.deepEqual(missingItems.map(({ item }) => item.id), [], `invocations without ${lang} text`);
    const knownChapters = new Set(hisn.chapters.map((chapter) => String(chapter.id)));
    const knownItems = new Set(items.map(({ item }) => String(item.id)));
    for (const id of Object.keys(translation.chapters)) assert.ok(knownChapters.has(id), `unknown chapter ${id}`);
    for (const id of Object.keys(translation.items)) assert.ok(knownItems.has(id), `unknown item ${id}`);
  });

  test(`${lang} translations are clean text: typographic apostrophes, no markup, no mojibake`, () => {
    const texts = [...Object.values(translation.chapters), ...Object.values(translation.items)];
    for (const text of texts) {
      assert.ok(!text.includes("'"), `straight apostrophe in: ${text.slice(0, 60)}`);
      assert.ok(!BROKEN_TEXT.test(text), `markup or mojibake in: ${text.slice(0, 60)}`);
      assert.equal(text, text.trim());
      assert.ok(!/\s{2,}/.test(text), `double space in: ${text.slice(0, 60)}`);
    }
  });
}

test("search finds a chapter by its translated title, by Arabic without vowel signs, and rejects nonsense", () => {
  const index = buildHisnSearchIndex(hisn.chapters, fr);
  const byTitle = searchHisnIndex(index, "avant de dormir");
  assert.ok(byTitle.chapters.some((chapter) => chapter.id === 28));
  const byArabic = searchHisnIndex(index, "اذكار النوم");
  assert.ok(byArabic.chapters.some((chapter) => chapter.id === 28), "Arabic search ignores diacritics");
  const byText = searchHisnIndex(index, "ayat al kursi");
  assert.ok(byText.itemTotal > 0, "the translated instruction is searchable");
  assert.equal(searchHisnIndex(index, "wxcvbn").itemTotal, 0);
  assert.equal(searchHisnIndex(index, "   "), null, "an empty query is not a search");
});
