import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 546, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.setDefaultTimeout(60000);
await page.goto('http://localhost:3002/page/566', { waitUntil: 'domcontentloaded' });
await page.waitForSelector('.reader-fullscreen-trigger', { timeout: 90000 });
await page.waitForTimeout(3000);
const steps = [];
steps.push('trigger visible: ' + await page.locator('.reader-fullscreen-trigger').first().isVisible());
const mushaf = page.locator('button:has-text("Mushaf")').first();
steps.push('mushafBtn: ' + await mushaf.count() + ' visible: ' + (await mushaf.count() ? await mushaf.isVisible() : '-'));
if (await mushaf.count()) { await mushaf.click({ timeout: 5000 }).catch(e => steps.push('mushaf click err')); await page.waitForTimeout(3000); }
steps.push('pane classes: ' + await page.evaluate(() => document.querySelector('.quran-mode-pane')?.className.slice(0,80)));
steps.push('shell now: ' + await page.locator('.qcm-page-shell').count());
await page.screenshot({ path: '.scratch-diag/shots/dbg1.png' });
await page.locator('.reader-fullscreen-trigger').first().click({ timeout: 5000 }).catch(e => steps.push('fs click err: ' + e.message.split('\n')[0]));
await page.waitForTimeout(4000);
steps.push('portal: ' + await page.locator('.mfp-portal-root').count() + ' shell: ' + await page.locator('.mfp-portal-root .qcm-page-shell').count());
await page.screenshot({ path: '.scratch-diag/shots/dbg2.png' });
console.log(steps.join('\n'));
await browser.close();
