import { useEffect, useMemo, useState } from "react";
import { BarChart3, Brain, CalendarDays, Check, ChevronRight, RotateCcw, Sparkles, Target } from "lucide-react";
import { getSurah } from "../../data/surahs";
import TAJWID_RULES from "../../data/tajwidRules";
import { getReadingDates } from "../../services/historyService";
import { clearKhatmaGoal, getKhatmaGoal, getKhatmaStats, KHATMA_PRESETS, setKhatmaGoal } from "../../services/khatmaService";
import { getAllMemorized, setMemorizationLevel } from "../../services/memorizationService";
import { getPosition, getSettings } from "../../services/storageService";
import { getTodayWird, getWirdHistory, markWirdCompleted, resetTodayWird } from "../../services/wirdService";
import { buildQuizQuestions, getMemorizationSummary, getWirdProgress, summarizeStudyWeek } from "./studyModel";

const sections = [
  { id: "today", label: "Aujourd'hui", icon: Target }, { id: "khatma", label: "Khatma", icon: CalendarDays },
  { id: "memory", label: "Memorisation", icon: Brain }, { id: "quiz", label: "Quiz tajwid", icon: Sparkles },
  { id: "stats", label: "Statistiques", icon: BarChart3 },
];
const Metric = ({ value, label }) => <div className="modern-study-metric"><strong>{value}</strong><span>{label}</span></div>;
const LevelControl = ({ item, onChange }) => <div className="modern-study-level" aria-label={`Niveau de memorisation ${item.surah}:${item.ayah}`}>{[1, 2, 3, 4, 5].map((level) => <button aria-label={`Niveau ${level}`} className={level <= item.level ? "is-active" : ""} key={level} onClick={() => onChange(level === item.level ? 0 : level)} type="button">{level}</button>)}</div>;

export function ModernStudyPage() {
  const [section, setSection] = useState("today");
  const [today, setToday] = useState(null); const [history, setHistory] = useState([]); const [readingDates, setReadingDates] = useState([]);
  const [memory, setMemory] = useState(() => getAllMemorized()); const [goal, setGoal] = useState(() => getKhatmaGoal());
  const [reference, setReference] = useState("2:255"); const [quizIndex, setQuizIndex] = useState(0); const [quizScore, setQuizScore] = useState(0); const [quizAnswer, setQuizAnswer] = useState(null);
  const [settings, setSettings] = useState(() => getSettings()); const quiz = useMemo(() => buildQuizQuestions(TAJWID_RULES, 5), []);
  const refreshWird = async () => { const [record, records, dates] = await Promise.all([getTodayWird(), getWirdHistory(7), getReadingDates(7)]); setToday(record); setHistory(records); setReadingDates(dates); };
  useEffect(() => { refreshWird().catch(() => setToday({ pagesRead: 0, ayahsRead: 0, completed: false })); }, []);
  useEffect(() => { const sync = (event) => setSettings(event.detail || getSettings()); window.addEventListener("modern-preferences-change", sync); return () => window.removeEventListener("modern-preferences-change", sync); }, []);
  const wird = getWirdProgress(today || {}, settings.wirdGoalAmount); const week = summarizeStudyWeek(history, readingDates); const memorySummary = getMemorizationSummary(memory);
  const currentPage = Number(getPosition()?.page) || 1; const khatma = goal ? getKhatmaStats(currentPage) : null; const activeQuestion = quiz[quizIndex];
  const saveMemory = (event) => { event.preventDefault(); const [surah, ayah] = reference.split(":").map(Number); if (!(surah >= 1 && surah <= 114 && ayah >= 1 && ayah <= (getSurah(surah)?.ayahs || 0))) return; setMemorizationLevel(surah, ayah, 1); setMemory(getAllMemorized()); };
  const updateMemory = (item, level) => { setMemorizationLevel(item.surah, item.ayah, level); setMemory(getAllMemorized()); };
  const answerQuiz = (choice) => { if (quizAnswer) return; setQuizAnswer(choice); if (choice === activeQuestion.answer) setQuizScore((score) => score + 1); };

  return <main className="modern-study" id="modern-main">
    <header><div><p className="modern-eyebrow">Progresser avec regularite</p><h1>Votre espace d'etude.</h1></div><p>Un suivi simple pour lire, memoriser et approfondir sans perdre le fil.</p></header>
    <nav aria-label="Sections d'etude" className="modern-study-tabs">{sections.map(({ id, label, icon: Icon }) => <button aria-pressed={section === id} className={section === id ? "is-active" : ""} key={id} onClick={() => setSection(id)} type="button"><Icon size={18} />{label}</button>)}</nav>
    {section === "today" && <section className="modern-study-section"><div className="modern-study-intro"><p className="modern-eyebrow">Wird quotidien</p><h2>{wird.completed ? "Objectif accompli" : `${wird.remaining} page${wird.remaining > 1 ? "s" : ""} a lire`}</h2><p>{wird.current} sur {wird.target} pages aujourd'hui.</p></div><div className="modern-study-main"><div className="modern-study-progress"><span style={{ width: `${wird.percentage}%` }} /></div><div className="modern-study-metrics"><Metric value={`${wird.percentage}%`} label="objectif" /><Metric value={wird.ayahsRead} label="versets" /><Metric value={today?.sessionsCount || 0} label="sessions" /></div><div className="modern-study-actions"><a className="modern-study-primary" href="/">Continuer la lecture <ChevronRight size={18} /></a><button onClick={async () => { await markWirdCompleted(!wird.completed); await refreshWird(); }} type="button"><Check size={18} />{wird.completed ? "Rouvrir" : "Marquer termine"}</button><button aria-label="Reinitialiser le wird" onClick={async () => { await resetTodayWird(); await refreshWird(); }} title="Reinitialiser" type="button"><RotateCcw size={18} /></button></div></div></section>}
    {section === "khatma" && <section className="modern-study-section"><div className="modern-study-intro"><p className="modern-eyebrow">Objectif de lecture</p><h2>Planifier une khatma</h2><p>La cadence s'adapte a la page {currentPage}, votre derniere position connue.</p></div><div className="modern-study-main">{khatma ? <><div className="modern-study-metrics"><Metric value={`${khatma.pct}%`} label="parcouru" /><Metric value={khatma.dailyQuota} label="pages / jour" /><Metric value={khatma.remainingDays} label="jours restants" /></div><div className="modern-study-progress"><span style={{ width: `${khatma.pct}%` }} /></div><p className="modern-study-note">Objectif: page {khatma.expectedPage} aujourd'hui. Vous etes {khatma.onTrack ? "dans le rythme" : "en retard sur le rythme"}.</p><button onClick={() => { clearKhatmaGoal(); setGoal(null); }} type="button">Supprimer cet objectif</button></> : <div className="modern-study-presets">{KHATMA_PRESETS.map((preset) => <button key={preset.days} onClick={() => setGoal(setKhatmaGoal({ targetDays: preset.days, startPage: currentPage }))} type="button"><strong>{preset.labelFr}</strong><span>{preset.pagesDay} pages par jour</span></button>)}</div>}</div></section>}
    {section === "memory" && <section className="modern-study-section"><div className="modern-study-intro"><p className="modern-eyebrow">Memorisation</p><h2>Reviser par niveau</h2><p>1 signifie a decouvrir, 5 signifie maitrise.</p><div className="modern-study-metrics is-vertical"><Metric value={memorySummary.verses} label="versets" /><Metric value={memorySummary.mastered} label="maitrises" /><Metric value={`${memorySummary.averageLevel}/5`} label="niveau moyen" /></div></div><div className="modern-study-main"><form className="modern-study-add" onSubmit={saveMemory}><label htmlFor="memory-reference">Ajouter une reference</label><div><input id="memory-reference" inputMode="numeric" onChange={(event) => setReference(event.target.value)} pattern="[0-9]{1,3}:[0-9]{1,3}" value={reference} /><button type="submit">Ajouter</button></div></form>{!memory.length ? <p className="modern-study-empty">Aucun verset en memorisation.</p> : <div className="modern-study-memory-list">{memory.map((item) => <article key={`${item.surah}:${item.ayah}`}><a href={`/surah/${item.surah}/${item.ayah}`}><strong>{item.surah}:{item.ayah}</strong><span>{getSurah(item.surah)?.fr}</span></a><LevelControl item={item} onChange={(level) => updateMemory(item, level)} /></article>)}</div>}</div></section>}
    {section === "quiz" && <section className="modern-study-section"><div className="modern-study-intro"><p className="modern-eyebrow">Tajwid</p><h2>Reconnaitre les regles</h2><p>Question {Math.min(quizIndex + 1, quiz.length)} sur {quiz.length}</p></div><div className="modern-study-main">{quizIndex >= quiz.length ? <div className="modern-study-result"><Sparkles size={28} /><h3>{quizScore} / {quiz.length}</h3><p>{quizScore === quiz.length ? "Excellent, les regles sont bien acquises." : "Reprenez les regles manquees puis recommencez."}</p><button onClick={() => { setQuizIndex(0); setQuizScore(0); setQuizAnswer(null); }} type="button"><RotateCcw size={18} />Recommencer</button></div> : <><h3 className="modern-study-question">{activeQuestion.prompt}</h3><div className="modern-study-choices">{activeQuestion.choices.map((choice) => <button className={quizAnswer ? (choice === activeQuestion.answer ? "is-correct" : choice === quizAnswer ? "is-wrong" : "") : ""} disabled={Boolean(quizAnswer)} key={choice} onClick={() => answerQuiz(choice)} type="button">{choice}</button>)}</div>{quizAnswer && <button className="modern-study-next" onClick={() => { setQuizIndex((index) => index + 1); setQuizAnswer(null); }} type="button">Question suivante <ChevronRight size={18} /></button>}</>}</div></section>}
    {section === "stats" && <section className="modern-study-section"><div className="modern-study-intro"><p className="modern-eyebrow">Sept derniers jours</p><h2>Votre regularite</h2><p>Lecture et objectifs reunis dans une seule vue.</p></div><div className="modern-study-main"><div className="modern-study-metrics is-large"><Metric value={week.activeDays} label="jours actifs" /><Metric value={week.pagesRead} label="pages lues" /><Metric value={week.ayahsRead} label="versets" /><Metric value={week.sessions} label="sessions" /><Metric value={week.completedDays} label="objectifs atteints" /></div></div></section>}
  </main>;
}
