/**
 * Integrate raw Tarteel/QUL downloads into the app's served corpus.
 *
 * QUL publishes no public text API (only /api/v1/chapters.json answers), so
 * the data has to arrive as files. This script turns those files into the same
 * shape the reader already loads, and refuses to produce a half-integrated
 * corpus: a missing file, an unexpected shape or a short verse count all stop
 * the run before anything is written.
 *
 * Every output file is recorded in a manifest with its sha256, the same way
 * src/constants/warshSource.js pins its own sources. The point is that a
 * change in the upstream text has to arrive through a reviewed revision, not
 * silently repaint a riwaya under a build that readers already have.
 *
 * Usage: npm run integrate:qul
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { decodeContainer } from "./lib/qul-container.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const IN = join(ROOT, "vendor", "qul");
const OUT = join(ROOT, "public", "data", "qul");

const SURAHS = 114;
// Verse counts differ by numbering. Madinah/Warsh numbering is 6214, Kufan
// (which the Hafs mushaf follows) is 6236; using one figure for both would
// reject a perfectly good download, so the expectation is per dataset.
const EXPECTED_VERSES = {
  "warsh-ayah": 6214,
  "warsh-wbw": 6214,
  "hafs-ayah": 6236,
  "hafs-wbw": 6236,
};

const INPUTS = [
  { file: "warsh-ayah.json", key: "warsh-ayah", label: "Warsh (ayah by ayah)" },
  { file: "warsh-wbw.json", key: "warsh-wbw", label: "Warsh (word by word)" },
  { file: "hafs-ayah.json", key: "hafs-ayah", label: "Hafs Kufan (ayah by ayah)" },
  { file: "hafs-wbw.json", key: "hafs-wbw", label: "Hafs Kufan (word by word)" },
];

const fail = (msg) => {
  console.error(`[integrate:qul] FAIL ${msg}`);
  process.exit(1);
};

function sha256(buf) {
  return createHash("sha256").update(buf).digest("hex");
}

/**
 * Tarteel ships either `{ "1:1": {...}, "1:2": {...} }` or a bare array of the
 * same records. Normalising here means the reader never has to know which.
 */
function toVerseMap(payload) {
  if (Array.isArray(payload)) {
    return new Map(
      payload
        .map((v) => [String(v.verse_key ?? v.key ?? ""), v])
        .filter(([k]) => k.includes(":")),
    );
  }
  if (payload && typeof payload === "object") {
    return new Map(Object.entries(payload).filter(([k]) => k.includes(":")));
  }
  return null;
}

function extractText(record) {
  if (!record || typeof record !== "object") return null;
  return record.text ?? record.text_warsh ?? record.text_qpc_hafs ?? null;
}

const present = INPUTS.filter((i) => existsSync(join(IN, i.file)));
if (!present.length) {
  fail(`no QUL file found in vendor/qul/. See vendor/qul/README.md for the list.`);
}

console.log(`[integrate:qul] found ${present.length}/${INPUTS.length} file(s) in vendor/qul/`);

const manifest = {
  generatedAt: new Date().toISOString(),
  source: "Tarteel Quranic Universal Library (qul.tarteel.ai)",
  note: "Generated by scripts/integrate-qul.mjs. Do not hand-edit: regenerate instead.",
  datasets: {},
};

const problems = [];
const staged = [];

for (const input of present) {
  let written = 0;
  let blank = 0;
  const raw = readFileSync(join(IN, input.file));
  const { body, encoding } = decodeContainer(raw);
  let payload;
  try {
    payload = JSON.parse(body.toString("utf8"));
  } catch (e) {
    fail(`${input.file} is not valid JSON (${encoding}): ${e.message}`);
  }

  const verses = toVerseMap(payload);
  if (!verses) fail(`${input.file} is neither a verse-keyed object nor an array`);

  // A corpus that does not carry every verse means the download was truncated
  // or a chapter is missing; writing it would put a short riwaya in front of a
  // reader with no indication of it.
  const expected = EXPECTED_VERSES[input.key];
  if (expected && verses.size < expected) {
    problems.push(`${input.file}: ${verses.size} verses, expected ${expected}`);
  }

  const bySurah = new Map();
  for (const [key, record] of verses) {
    const [s] = key.split(":");
    if (!bySurah.has(s)) bySurah.set(s, []);
    bySurah.get(s).push([key, record]);
  }
  if (bySurah.size !== SURAHS) {
    problems.push(`${input.file}: ${bySurah.size} surahs, expected ${SURAHS}`);
  }

  // Build every surah in memory first. Writing as we go would leave a partial
  // corpus on disk when a later dataset fails the structure check, which is
  // exactly the state this script exists to prevent.
  const outDir = join(OUT, input.key);
  const files = [];
  const payloads = [];
  const digest = createHash("sha256");

  for (const surah of [...bySurah.keys()].sort((a, b) => Number(a) - Number(b))) {
    const rows = bySurah.get(surah).sort((a, b) => Number(a[0].split(":")[1]) - Number(b[0].split(":")[1]));
    const body = { surah: Number(surah), verses: Object.fromEntries(rows) };
    const text = JSON.stringify(body);
    payloads.push({ file: `${String(surah).padStart(3, "0")}.json`, text });
    digest.update(text);
    files.push(payloads[payloads.length - 1].file);
    written += rows.length;
    for (const [, record] of rows) if (!extractText(record)) blank += 1;
  }

  manifest.datasets[input.key] = {
    label: input.label,
    sourceFile: input.file,
    sourceEncoding: encoding,
    sourceSha256: sha256(raw),
    surahs: bySurah.size,
    verses: written,
    versesWithoutText: blank,
    contentSha256: digest.digest("hex"),
    files,
  };
  staged.push({ dir: outDir, payloads });

  console.log(
    `[integrate:qul] ${input.key}: ${bySurah.size} surahs, ${written} verses` +
      (blank ? `, ${blank} without text` : ""),
  );
}

if (problems.length) {
  fail(`structure check failed:\n  - ${problems.join("\n  - ")}`);
}

// Nothing has touched public/data yet. Only now, with every dataset validated,
// is it safe to replace what the reader serves.
for (const { dir, payloads } of staged) {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  for (const { file, text } of payloads) writeFileSync(join(dir, file), text, "utf8");
}

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
console.log(`[integrate:qul] wrote public/data/qul/manifest.json`);
console.log("[integrate:qul] OK");
